name: todo
publish_to: 'none'

environment:
  sdk: ^3.8.0-210.0.dev

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
