name: todo
publish_to: 'none'

environment:
  sdk: ^3.8.0-210.0.dev

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
